# Generated by Django 4.2.6 on 2023-10-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='certications',
            field=models.TextField(default=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='github_url',
            field=models.CharField(default=11, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='hobbies',
            field=models.CharField(default=11, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='linkedin_url',
            field=models.CharField(default=11, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='portfolio_url',
            field=models.CharField(default=11, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='projects',
            field=models.TextField(default=11),
            preserve_default=False,
        ),
    ]
